apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: europe-west2-docker.pkg.dev/gothic-album-364814/pauljs-io/homepage
  newTag: 1.8.0

commonLabels:
  env: prod

patchesJson6902:
  - target:
      kind: Ingress
      version: v1
      name: homepage
    patch: |-
      - op: add
        path: metadata/annotations
        value: 
          nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  - target:
      kind: Ingress
      version: v1
      name: homepage
    patch: |- 
      - op: add
        path: /spec/tls/0/hosts/-
        value: www.pauljs.io