apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
spec:
  generators:
  - git:
      repoURL: {{ .Values.spec.source.repoURL }}
      revision: {{ .Values.spec.source.targetRevision }}
      directories:
      - path: apps/*/overlays/*
      - path: apps/*/overlays/dev
        exclude: true
  template:
    metadata:
      name: '{{path[0]}}'
    spec:
      source:
        repoURL: {{ .Values.spec.source.repoURL }}
        targetRevision: {{ .Values.spec.source.targetRevision }}
        path: '{{path}}'
      project: default
      destination:
        server: {{ .Values.spec.destination.server }}
        namespace: '{{path[1]}}'
