apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

resources:
- ../../base

replacements:
  - source:
      kind: Ingress
      fieldPath: metadata.labels.pull-request
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - spec.rules.[host=pauljs.io].host
        options:
          delimiter: "."
          index: -1
      - select:
          kind: Ingress
        fieldPaths:
          - spec.tls.[secretName=homepage-cert].hosts.0
        options:
          delimiter: "."
          index: -1