apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  generators:
  - git:
      repoURL: "https://github.com/paulsilcock/app-of-apps"
      revision: HEAD
      directories:
      - path: apps/*/overlays/*
      - path: apps/*/overlays/dev
        exclude: true
  template:
    metadata:
      name: '{{path[0]}}'
    spec:
      source:
        repoURL: "https://github.com/paulsilcock/app-of-apps"
        targetRevision: HEAD
        path: '{{path}}'
      project: default
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{path[1]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
