apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
spec:
  generators:
  - git:
      repoURL: "https://github.com/paulsilcock/app-of-apps"
      revision: HEAD
      directories:
      - path: cluster/*/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      source:
        repoURL: "https://github.com/paulsilcock/app-of-apps"
        targetRevision: HEAD
        path: '{{path}}'
      project: default
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{path[0]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
