apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: europe-west2-docker.pkg.dev/gothic-album-364814/pauljs-io/homepage
  newTag: 1.8.0

commonLabels:
  env: staging

replacements:
- source:
    fieldPath: metadata.labels.env
    kind: Ingress
  targets:
  - fieldPaths:
    - spec.rules.[host=pauljs.io].host
    options:
      delimiter: .
      index: -1
    select:
      kind: Ingress
  - fieldPaths:
    - spec.tls.[secretName=homepage-cert].hosts.*
    options:
      delimiter: .
      index: -1
    select:
      kind: Ingress
