apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: europe-west2-docker.pkg.dev/gothic-album-364814/pauljs-io/homepage
  newTag: 1.0.0

commonLabels:
  env: staging

replacements:
  - source:
      kind: Ingress
      fieldPath: metadata.labels.env
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - spec.rules.0.host
        options:
          delimiter: "."
          index: -1
      - select:
          kind: Ingress
        fieldPaths:
          - spec.tls.0.hosts.0
        options:
          delimiter: "."
          index: -1