name: Deploy
on:
  workflow_dispatch:
    inputs:
      app:
        description: Application to update
        required: true
        type: string
      tag:
        description: New tag
        required: true
        type: string
      env:
        description: Environment to update
        type: choice
        options:
          - staging # Only allow auto-update of staging (for now!)
        required: true

jobs:
  update_manifests:
    env:
      NEW_IMAGE: "europe-west2-docker.pkg.dev/gothic-album-364814/pauljs-io/${{ github.event.inputs.app }}:${{ github.event.inputs.tag }}"
      APP: ${{ github.event.inputs.app }}
      TAG: ${{ github.event.inputs.tag }}
      ENV: ${{ github.event.inputs.env }}

    name: "Release ${{ github.event.inputs.app }} v${{ github.event.inputs.tag }} to ${{ github.event.inputs.env }}"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: imranismail/setup-kustomize@v2

      - name: Update deployed image
        run: | 
          cd apps/${{ env.APP }}/overlays/${{ env.ENV }}
          kustomize edit set image ${{ env.NEW_IMAGE }}
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add kustomization.yaml
          git commit -m 'Updates `${{ env.ENV }}`/`${{ env.APP }} to `v${{ env.TAG }}`' -m '[skip ci]'
          git push
      