apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homepage-pr
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: paulsilcock
          repo: homepage
        requeueAfterSeconds: 180
  template:
    metadata:
      name: "homepage-{{branch}}-{{number}}"
    spec:
      source:
        repoURL: "https://github.com/paulsilcock/app-of-apps"
        targetRevision: HEAD
        path: apps/homepage/overlays/dev
        kustomize:
          commonLabels:
            pull-request: "pr{{number}}"
          images: 
            - "europe-west2-docker.pkg.dev/gothic-album-364814/pauljs-io/homepage:{{head_sha}}"
      project: default
      destination:
        server: "https://kubernetes.default.svc"
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
